import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers, utils } from "ethers"
import { useEffect, useState } from "react"
import { useRouter } from 'next/router'
import 'react-calendar/dist/Calendar.css';
import { useEthers, useEtherBalance, useContractFunction, useContractCall } from '@usedapp/core'
import abi from "../utils/RaffleFactory.json"
import { Contract } from '@ethersproject/contracts'
import { factoryContractAddress } from '../utils/contract-utils'
const create = () => {
  const { activateBrowserWallet, deactivate, account, library } = useEthers();

  //raffleFactory vars
  const contractABI = abi.abi;
  const [tokenAddress, setTokenAddress] = useState('') // nft contract address
  const [tokenId, setTokenId] = useState(0) //nft id
  const [name, setName] = useState('');

  //nft contract vars
  const nftIface = new utils.Interface([
      'function approve(address to, uint256 tokenId) external',
      'function getApproved(uint256 tokenId) external view returns (address operator)', 
  ])
  const result = useContractCall( library && {
      abi: nftIface,
      address: tokenAddress,
      method: 'getApproved',
      args: [tokenId]
  });
  const nftContract = null;
  const {state, send} = useContractFunction(
    nftContract, 'approve');


  // const createRaffle = () =>{
  //   send(tokenAddress, tokenId);
  // }

  const createRaffle = async() =>{
    try {
      const { ethereum } = window;
      if (ethereum) {
        const provider = new ethers.providers.Web3Provider(ethereum);
        const signer = provider.getSigner();
        const raffleContract = new ethers.Contract(factoryContractAddress, contractABI, signer);

        console.log("waiting for nft approval");
        const nftContract = new ethers.Contract(tokenAddress, nftIface, signer);
        const nftApprove = await nftContract.approve(factoryContractAddress, tokenId, {gasLimit: 300000});
        console.log("Mining...", nftApprove.hash);

        await nftApprove.wait();
        console.log("Mined -- ", nftApprove.hash);

        const raffleCreate = await raffleContract.createRaffle(tokenAddress, tokenId, name, {gasLimit: 300000});
        console.log("Mining...", raffleCreate.hash);

        await raffleCreate.wait();
        console.log("Mined -- ", raffleCreate.hash);

      } else {
        console.log("Ethereum object doesn't exist!");
      }
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div class=" min-w-screen min-h-screen">
    <Head>
        <title>legit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main class="bg-slate-50 min-w-screen min-h-screen">
      <div className="flex justify-center">
        <div className="w-1/2 flex flex-col pb-12">
          <h2 className='mt-10 font-bold text-5xl'>create raffle</h2>
          <input
            placeholder="raffle name"
            className="mt-8 border rounded p-4"
            onChange={e => setName(e.target.value)}
          />

          <input
            placeholder="token address"
            className="mt-8 border rounded p-4"
            onChange={e => setTokenAddress(e.target.value)}
          />
          <input
            placeholder="token id"
            className="mt-8 border rounded p-4"
            onChange={e => setTokenId(e.target.value)}
          />
          <button onClick={createRaffle} className="font-bold mt-4 bg-green-500 text-white rounded p-4 shadow-lg hover:bg-green-700">
            create raffle
          </button>
        </div>
      </div>
    </main>
  </div>
  )
}

export default create