import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react"
import { useRouter } from 'next/router'
import { useEthers, useEtherBalance } from '@usedapp/core'
import Card from '../components/Card'
const dashboard = () => {
  const { activateBrowserWallet, deactivate, account } = useEthers()

  return (
    <div className="bg-slate-50 min-w-screen min-h-screen">
      <Head>
          <title>legit</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-50 min-w-screen min-h-screen">

        {!account && 
        <div className="flex justify-center">
          <div>
          <div>
            uh oh, your wallet isnt connected
          </div>
          <div>
            connect wallet to ethereum rinkeby
          </div>
          <button
          className="bg-gray-200 hover:bg-gray-300 px-4 py-2 rounded"
          onClick={activateBrowserWallet}>connect wallet</button>
          </div>
        </div>
        }
        {account && 
          <div >
            <div className="flex justify-center">
              raffles made
              <Card/>
              <Card/>

            </div> 
            <div className="flex justify-center">
              raffles entered
              <Card/>
              <Card/>
            </div>
          </div>   
        }
      </main>
  </div>
      )
}

export default dashboard