import Head from 'next/head'
import Image from 'next/image'
import navbar from './components/navbar'
import { useEthers, useEtherBalance } from '@usedapp/core'

export default function Home() {
  const { activateBrowserWallet, deactivate, account } = useEthers()


  return (
    <div class="bg-slate-50 min-w-screen min-h-screen">
      <Head>
          <title>legit</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-slate-50 min-w-screen min-h-screen">

        {!account && <button
                       onClick={activateBrowserWallet}>connect wallet</button>}
        {account && 
          <div>
            <div>
              raffles made
            </div> 
            <div>
              raffles entered
            </div>
          </div>   
        }
      </main>
  </div>
  )
}
