import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers"
import { useEffect, useState } from "react"
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { useRouter } from 'next/router'
import { useEthers, useEtherBalance, useContractFunction } from '@usedapp/core'
import Calendar from 'react-calendar'
import 'react-calendar/dist/Calendar.css';

const raffle = () => {
  const { activateBrowserWallet, deactivate, account } = useEthers();

  return (
<div class=" min-w-screen min-h-screen">
    <Head>
        <title>legit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <main class="bg-slate-50 min-w-screen min-h-screen">
    <div className="flex justify-center">
        <div className="w-1/2 flex flex-col pb-12 content-center">
          <h2 className='mt-10 font-bold text-5xl'>raffle title</h2>
          <h3 className='mt-5 text-5md'>raffle description</h3>
          <div class="mt-14 p-6 max-w-md bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">enter raffle</h5>
            <p class="mb-3 font-normal text-gray-500">follow the steps below to add yourself to the raffle</p>
            {!account &&
            <div className="mt-10 flow-root">
              <h3 className='font-bold text-5md float-left'>connect wallet</h3>
              <button onClick={activateBrowserWallet} class="float-right inline-flex items-center py-2 px-4 text-sm font-medium text-center text-white bg-slate-500 rounded-full hover:bg-slate-700 focus:ring-4 focus:ring-blue-300  ">
                <Icon className="ml-0.5" fill="#FFFFFF" size={20} svg="creditCard"/>
                  connect wallet 
              </button>
            </div>}
            {account &&
            <div className="mt-10 flow-root">
              ✅
              <h3 className='text-green-600 font-bold text-5md float-left'>connect wallet</h3>
            </div>}
            <div className="flow-root mt-10">
              <h3 className='font-bold text-5md float-left'>connect twitter</h3>
              <a href="#" class="float-right inline-flex items-center py-2 px-4 text-sm font-medium text-center text-white bg-sky-400 rounded-full hover:bg-sky-600 focus:ring-4 focus:ring-blue-300  ">
                <Icon className="ml-0.5" fill="#FFFFFF" size={20} svg="twitter"/>   
                  connect twitter 
              </a>
            </div>
            <div className="flow-root mt-10">
              <h3 className='font-bold text-5md float-left'>connect discord</h3>
              <a href="#" class="float-right inline-flex items-center py-2 px-4 text-sm font-medium text-center text-white bg-indigo-600 rounded-full hover:bg-indigo-800 focus:ring-4 focus:ring-blue-300  ">
                  <Icon className="ml-0.5" fill="#FFFFFF" size={20} svg="discord"/>
                  connect discord 
              </a>
            </div>
            <div className="flex mt-10">
              <button className="grow font-bold mt-4 bg-green-500 text-white rounded p-4 shadow-lg hover:bg-green-700">
                create raffle
              </button>
            </div>
          </div>
        </div>
      </div>
    </main>
    <Footer/>
  </div>  
  )
}

export default raffle